info:
  version: 1.0.2
  description: NSSF initial local configuration

configuration:
  nssfName: NSSF
  sbi:
    scheme: http
    registerIPv4: nssf.free5gc.org
    bindingIPv4: nssf.free5gc.org
    port: 8000
    tls:
      pem: cert/nssf.pem
      key: cert/nssf.key
  serviceNameList:
    - nnssf-nsselection
    - nnssf-nssaiavailability
  nrfUri: http://nrf.free5gc.org:8000
  nrfCertPem: cert/nrf.pem

  supportedPlmnList:
    - mcc: 208
      mnc: 93

  # 支援的 S-NSSAI 列表 (與 AMF、SMF 對應)
  supportedNssaiInPlmnList:
    - plmnId:
        mcc: 208
        mnc: 93
      supportedSnssaiList:
        - sst: 1
          sd: 010203
        - sst: 2
          sd: 112233

  # Network Slice Instance (NSI) 清單
  # 每個 S-NSSAI 對應一個 NSI，可以自行定義 nsiId
  nsiList:
    - snssai:
        sst: 1
        sd: 010203
      nsiInformationList:
        - nrfId: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
          nsiId: 101
    - snssai:
        sst: 2
        sd: 112233
      nsiInformationList:
        - nrfId: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
          nsiId: 102

  # 簡化的 AMF Set 清單，可根據需要配置
  # 若您有多個 AMF，也可定義多個 AMF Set
  amfSetList:
    - amfSetId: 1
      # AMF的實際 nfId 啟動後由 NRF 註冊決定，可先留空或日後補上
      # 此處僅做範例，可依實際狀況調整
      amfList:
        - ffa2e8d7-3275-49c7-8631-6af1df1d9d26
      nrfAmfSet: http://nrf.free5gc.org:8000/nnrf-nfm/v1/nf-instances
      supportedNssaiAvailabilityData:
        - tai:
            plmnId:
              mcc: 208
              mnc: 93
            tac: 000001
          supportedSnssaiList:
            - sst: 1
              sd: 010203
            - sst: 2
              sd: 112233

  # TA 清單: 將同一個 TAI 列出對應的支援切片
  taList:
    - tai:
        plmnId:
          mcc: 208
          mnc: 93
        tac: 000001
      accessType: 3GPP_ACCESS
      supportedSnssaiList:
        - sst: 1
          sd: 010203
        - sst: 2
          sd: 112233

logger:
  enable: true
  level: info
  reportCaller: false
